lamp:
  nacos:
    ip: ${NACOS_IP:@nacos.ip@}
    port: ${NACOS_PORT:@nacos.port@}
    namespace: ${NACOS_NAMESPACE:@nacos.namespace@}
    username: ${NACOS_USERNAME:@nacos.username@}
    password: ${NACOS_PASSWORD:@nacos.password@}
    group: DEFAULT_GROUP

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: '@project.artifactId@'
  profiles:
    active: '@profile.active@'
  config:
    import:
      - nacos:common.yml?group=${lamp.nacos.group}&refresh=true
      - nacos:${spring.application.name}.yml?refresh=true
  cloud:
    nacos:
      server-addr: ${lamp.nacos.ip}:${lamp.nacos.port}
      username: ${lamp.nacos.username}
      password: ${lamp.nacos.password}
      config:
        file-extension: yml
        namespace: ${lamp.nacos.namespace}
        enabled: true
      discovery:
        server-addr: ${lamp.nacos.ip}:${lamp.nacos.port}
        namespace: ${lamp.nacos.namespace}
        metadata: # 元数据，用于权限服务实时获取各个服务的所有接口
          management.context-path: ${server.servlet.context-path:}${spring.mvc.servlet.path:}${management.endpoints.web.base-path:}
          gray_version: zuihou
  boot:
    admin:
      discovery:
        ignored-instances-metadata:
          sba: ignore
          meta-v: 1.0.0


# 用于/actuator/info
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
